version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: proxl-mysql
    restart: always
    command: ${MYSQL_OPTIONS}
    volumes:
      - ${MYSQL_DATA_DIRECTORY}:/var/lib/mysql
      - ./database_scripts/install:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${PROXL_DATABASE_NAME}
  spectr:
    image: mriffle/spectr:1
    container_name: proxl-spectr
    restart: always
    volumes:
      - ${SPECTR_UPLOAD_DIRECTORY}:/data/upload
      - ${SPECTR_STORAGE_DIRECTORY}:/data/storage
      - ${PROXL_UPLOAD_DIRECTORY}:/data/proxl_upload
  importer:
    image: mriffle/proxl-importer:2
    container_name: proxl-importer
    restart: always
    depends_on:
      - db
    volumes:
      - ${PROXL_UPLOAD_DIRECTORY}:/data/proxl_upload
    environment:
      proxl_DB_USER: ${MYSQL_USER}
      proxl_DB_PASSWORD: ${MYSQL_PASSWORD}
      proxl_DB_HOST_ADDRESS: db
      proxl_DB_HOST_PORT: 3306
      PROXL_DB_NAME: ${PROXL_DATABASE_NAME}
      proxl_JAVA_EXECUTE_PARAMS: ${IMPORTER_JAVA_OPTIONS}
      PROXL_WEB_APP_BASE_URL: ${PROXL_WEB_APP_BASE_URL}
  proxl:
    image: mriffle/proxl-webapp:2
    container_name: proxl-webapp
    restart: always
    depends_on:
      - db
    volumes:
      - ${PROXL_UPLOAD_DIRECTORY}:/data/proxl_upload
    environment:
      proxl_MYSQL_USER: ${MYSQL_USER}
      proxl_MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      PROXL_DATABASE_NAME: ${PROXL_DATABASE_NAME}
    ports:
      - 8080:8080
  smtp:
    image: bytemark/smtp
    container_name: proxl-smtp
    restart: always
    environment:
      RELAY_HOST: ${SMTP_HOST}
      RELAY_PORT: ${SMTP_PORT}
      RELAY_USERNAME: ${SMTP_USERNAME}
      RELAY_PASSWORD: ${SMTP_PASSWORD}
